### ISSUE TITLE
A wrong execution example in 7.3.29.3.3

### ISSUE THREAD

**Issue by myokoym** [groonga/groonga.org#14]
7.3.29. table_create — Groonga v4.0.7 documentation
http://groonga.org/docs/reference/commands/table_create.html#create-tag-index-table
http://groonga.org/ja/docs/reference/commands/table_create.html#create-tag-index-table

**Comment by kou** [comment]
Thanks for your report!
It'll be fixed in the next release.

**Comment by myokoym** [comment]
ありがとうございます！
追加でプルリクエストを出してみたんですが、logファイルって自動生成される感じでしたか？

**Comment by kou** [comment]
はい！ `make -C doc update-examples` で自動生成です。

**Comment by myokoym** [comment]
すみません、今回は手で修正してしまったので、次回はコマンドで確認するようにします！
