### ISSUE TITLE
Typo 筆意用 -> 必要

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga.org#15]
Hello 

I found typo. 

[筆意用](https://github.com/groonga/groonga.org/blob/gh-pages/ja/docs/reference/tokenizers.html#L1099)
- 誤: 筆意用
- 正: 必要

追伸: PRしようと思ったのですが、私の環境(Macだと、修正箇所以外のところが修正されたとみなされてしまい、不要な修正が含まれたPRとなってしまうため、場所のみお知らせします。

**Comment by myokoym** [comment]
ご報告ありがとうございます！
修正箇所へのリンクを張ってもらったので、わかりやすくて助かりました。
groonga/groonga#338 の方で修正して、groonga.orgにも反映させておきました。
