### ISSUE TITLE
例えば、 1.2 は 1.2 にしてください。

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga.org#16]
[例えば、 1.2 は 1.2 にしてください。](https://github.com/groonga/groonga.org/blob/gh-pages/ja/docs/reference/grn_expr/script_syntax.html#L124)

例えば、"1.2"は1.2に変換してくださいという意味でしょうか？

よろしくお願いします。

**Comment by kou** [comment]
「表記」が同じでわかりにくいのですが、「1.2は」の方の「1.2」は「数値」で「1.2に」の方の「1.2」は「数字」を意図していました。

「1.2（数値）は1.2（数字）にしてください」とするといいのかしら。。。

**Comment by hiroyuki-sato** [comment]
ありがとうございます。

個人的には次のような表記がわかりやすいように思います。

数値: 整数または浮動小数点として利用できるようにしてください。(1.2, -10, 314e-2など) 詳しくは[リテラル](http://groonga.org/ja/docs/reference/grn_expr/script_syntax.html?highlight=指数#literals) を参照してください。

**Comment by kou** [comment]
なるほど。リテラルのドキュメントを参照するのはいいですね！

ただ、ここのセクションは「データのエスケープ方法を説明する」という文脈なので、「利用できるようにしてください」というのはなじまないように感じました。

ということで、↓な感じだとどうでしょうか！？

> 数値: 整数リテラル（リンクにする）または浮動小数点数整数リテラル（リンクにする）に変換してください。例えば、1.2, -10, 314e-2といった具合です。

**Comment by hiroyuki-sato** [comment]
ありがとうございます。わかりやすいと思います。

**Comment by myokoym** [comment]
これは英語の方も直したほうがよさそうですね。あとで対応しておきます。

英語の修正はdoc/source以下のファイルを直接編集するのですが、
もし余裕があればpull requestをいただけると助かります。
https://github.com/groonga/groonga/blob/master/doc/source/reference/grn_expr/script_syntax.rst

**Comment by hiroyuki-sato** [comment]
ありがとうございます。

ドキュメントだけ更新してみました。

sphinxで確認をしたいのですが、configure --enable-documentしたら
環境構築に時間がかかりそうだったので取り急ぎパッチだけ添付します。

sphinxだけ実行する方法が簡単にわかれば教えてください。
よろしくお願いします。

``` patch
diff --git a/doc/source/reference/grn_expr/script_syntax.rst b/doc/source/reference/grn_expr/script_syntax.rst
index f57c221..1d097e3 100644
--- a/doc/source/reference/grn_expr/script_syntax.rst
+++ b/doc/source/reference/grn_expr/script_syntax.rst
@@ -65,8 +65,7 @@ input value. Here is a list how to escape user input value:

   * True value: Convert it to ``true``.
   * False value: Convert it to ``false``.
-  * Numerical value: Convert it to number. For example, ``1.2`` should
-    be converted to ``1.2``.
+  * Numerical value: Convert it :doc:`Integer` or :doc:`Float` ex) 1.2, -10, 314e-2
   * String value: Replace ``"`` with ``\"`` and ``\`` with ``\\`` in
     the string value and surround substituted string value by
     ``"``. For example, ``double " quote and back \ slash`` should be
```

**Comment by myokoym** [comment]
パッチありがとうございます！
Sphinxだけ実行する方法がわからなかったので、私の方で修正しました。
