### ISSUE TITLE
7.2.1.1. コマンドラインの説明

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga.org#17]
[7.2.1.1. コマンドライン](http://groonga.org/ja/docs/reference/output.html#command-line)

[ソース](https://github.com/groonga/groonga.org/blob/gh-pages/ja/docs/reference/output.html#L116)

`>`  というプロンプトが表示されます。クエリーインターフェイスでは `output_type`

意図した出力は上記のとおりのように思います。

**Comment by myokoym** [comment]
ご指摘ありがとうございます！修正しました！
