### ISSUE TITLE
一部ファイル名について

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga.org#19]
次のファイル名を小文字にすることは可能でしょうか？

OSXは大文字・小文字の区別がないため、ファイルを修正していなくても
次のファイルが修正されたと判定されてしまい、PRするのに不便です。

あと[Groongaドキュメント](http://groonga.org/ja/docs/)の内容を修正したPRを出す場合は
https://github.com/groonga/groonga.org/tree/gh-pages/ja/docs
ここを修正すればよいのでしょうか？

よろしくお願いします。

```
    modified:   senna/FrontPage.html
    modified:   senna/FrontPage.txt
    modified:   senna/_counter_FrontPage.html
    modified:   senna/_counter_FrontPage.txt
```

**Comment by kenhys** [comment]
groonga.org/senna以下のファイルについては、元の http://qwik.jp/senna/ のサービスがクローズされることにともない取り込んだものなので、対象となるファイルのリンクさえ適切であれば小文字にしてしまっても問題ないはずです。

http://groonga.org/ja/docs/ のドキュメントを修正したい場合には、groonga/groonga.orgではなくて、https://github.com/groonga/groonga/tree/master/doc/source 以下を変更する必要があります。

groonga/groonga.orgはあくまで生成済みのHTMLをコミットしているだけなので元データは↑のほうなんです。

**Comment by kenhys** [comment]
ドキュメントの修正を手伝ってもらう際の手順は以下にあります。
http://groonga.org/ja/docs/contribution.html 

ただ、OSXの場合は以下の記事がよりわかりやすいかも知れません。
http://qiita.com/tamano/items/7cc81f96699417677994

**Comment by hiroyuki-sato** [comment]
了解しました。ありがとうございます。そういう意味ではこちらの文字を大文字から小文字にしてもあまり意味がありませんね。いただいたURLを参考にします。
