### ISSUE TITLE
Groongaで学ぶ全文検索のイベントページ

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga.org#20]
[「Groongaで学ぶ全文検索」開催のお知らせ](http://groonga.org/ja/blog/2015/09/22/learn-full-text-search-with-groonga-announce.html)

の中にある[イベントページ](https://groonga.doorkeeper.jp/events/31859)
のリンクが10/2の終わったイベントになっています。

定期的に修正するか
[Groonga](https://groonga.doorkeeper.jp)
こっちの方がいいような気がします。

blogroongaのソースがわからなかったのでこちらにコメントしました。

11/6参加できそうだな〜と思ってらキャンセル待ちでした。人数徐々に増えてますね。

**Comment by kou** [comment]
ありがとうございます！
https://groonga.doorkeeper.jp/events/upcoming のリンクを入れてみました！

ちなみに、blogroongaのソースは https://github.com/groonga/groonga.org/tree/gh-pages/ja/_posts に転がっています。

11/6のやつはキャンセル待ちに登録してもらえますか？会場提供してくれる方に1人増えても大丈夫そうか聞いてみます。（最近は当日キャンセルがでることが多いので入れそうな気はします。）

**Comment by hiroyuki-sato** [comment]
ありがとうございます。よくよく見たら、次回のイベントは10月2日です。となっていますね。ここは(もう)なくてもいいような..気もします。
