### ISSUE TITLE
Convert Textile to Markdown

### ISSUE THREAD

**Issue by kou** [groonga/groonga.org#23]
GitHub will drop Textile support...: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

> Starting May 1st, 2016, GitHub Pages will no longer support Textile. If you are currently using Textile (Redcloth) to author your Jekyll site, you'll need to convert your site to use Markdown instead.

**Comment by kou** [comment]
.textile are exists at:
- https://github.com/groonga/groonga.org/tree/gh-pages/en/_posts
- https://github.com/groonga/groonga.org/tree/gh-pages/ja/_posts

**Comment by ohkubo** [comment]
Seems fixed by #24 and following commits (86ffad5ae370009fa7cf30ecc139127575f7fde3...00cdbbb674f47d8fdd55868bca4a5765654cdb9f).
I suggest closing this issue. :-)

**Comment by kou** [comment]
Good catch!
