### ISSUE TITLE
gitでのコンフリクトがそのままコミットされている箇所がある

### ISSUE THREAD

**Issue by trrk** [groonga/groonga.org#40]
タイトル通りですが、このようにgitのコンフリクトがそのままコミットされている箇所がありました。
https://github.com/groonga/groonga.org/blob/273ba12126f21bbb2848be4f41bc3d2ee03b0770/docs/searchindex.js

公式サイトでのクイック検索が機能しないことで気がつきました。
また、searchindex.js 以外にもこのような状態でコミットされているところがあるようです。

**Comment by kenhys** [comment]
報告ありがとうございます！

修正しておきました。とても助かりました！

**Comment by trrk** [comment]
検索も機能していい感じです。
手早い修正でした。ありがとうございます。
