### ISSUE TITLE
In mysql, groonga queries special characters (like *? /%) ￥#@）。 Syntax parsing errors and exceptions will occur

### ISSUE THREAD

**Issue by mmm8955405** [groonga/groonga.org#61]
SQLSTATE[42000]: Syntax error or access violation: 1064 failed to parse fulltext search keyword:

**Comment by mmm8955405** [comment]
TokenBigram  ！    Default syntax parser

**Comment by komainu8** [comment]
Could you how to reproduce this problem? 
I think that this problem is for Mroonga. Therefore, could you move this issue to https://github.com/mroonga/mroonga/issues ?

**Comment by mmm8955405** [comment]
OK, thank you very much
